FROM node:22-alpine3.20 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY server.js ./
COPY routes ./routes
COPY controllers ./controllers
COPY middleware ./middleware
COPY configs ./configs

FROM node:22-alpine3.20 AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/ ./
EXPOSE 3000
RUN addgroup -S -g 1001 appgroup && adduser -S -u 1001 -G appuser appgroup && chown -R 1001:1001 /app
USER 1001
CMD ["node","server.js"]