export default {
  testEnvironment: 'node',
  transform: {},
  testMatch: ['**/__tests__/integration/**/*.test.js'],
  coverageReporters: ['lcov', 'text', 'json-summary'],
  collectCoverageFrom: [
    '**/*.js',
    '!**/node_modules/**',
    '!**/__tests__/**',
    '!eslint.config.js',
    '!server.js',
    '!**/langgraph.js',
    '!configs/db.js',
    '!configs/gemini.js',
    '!configs/cloudinary.js',
    '!configs/model.js',
    '!babel.config.js',
    '!jest.unit.config.js',
    '!jest.integration.config.js',
    '!**/coverage/**',
  ],
  passWithNoTests: true,
};
