apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: server-backend
  labels:
    app: server
    role: stable
    environment: production
spec:
  selector:
    app: server
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: server-service
      protocol: TCP
      port: 80
      targetPort: 3000
