name: CI PIPELINE

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: server-backend/ai-website
  EKS_CLUSTER_NAME: AI-backend
  IMAGE_TAG: ${{github.sha}}
  # EKS_CLUSTER_NAME: server-backend

jobs:
  # Install and Cache Dependencies

  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{runner.os}}-node-${{hashFiles('server/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-node

  # Lint and Format Check
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{runner.os}}-node-${{hashFiles('server/package-lock.json')}}

      - name: Run ESlint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format:check

  # Unit tests + coverage
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{runner.os}}-node-${{hashFiles('server/package-lock.json')}}

      - name: Run unit tests with coverage
        run: npm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: server/coverage/
      - name: Check coverage threshold
        run: |
          COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          echo "Coverage: $COVERAGE%"
          if [ $(echo "$COVERAGE < 80" | bc -l) -eq 1 ]; then
            echo "Coverage $COVERAGE% is below 80% threshold"
          exit 1
          fi
  # Integration Test
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: server
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{runner.os}}-node-${{hashFiles('server/package-lock.json')}}

      - name: Run integration tests
        working-directory: server
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: npm run test:integration

  # Security Scanning
  security:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #Full history for secret scanning

      - name: Run Trufflehog (secret scanning)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{github.event.before}}
          head: ${{github.event.after}}
          extra_args: --only-verified

      # Static Application Security Testing
      - name: Run Semgrep (SAST)
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/default
            p/owasp-top-ten
            p/nodejs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: server

      # Dependency vulnerability scan
      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Run Snyk vulnerability scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        with:
          args: --severity-threshold=high --file=server/package.json

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #shallow clones disabled - sonarcloud needs full history for blame

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{runner.os}}-node-${{hashFiles('server/package-lock.json')}}

      # Download the coverage report generated in the unit-tests job
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: server/coverage/

      # sonarcloud scanner analysis
      # #   - Bugs & code smells
      #   - Security vulnerabilities (SAST)
      #   - Code duplication
      #   - Test coverage (from lcov.info)
      #   - Technical debt #
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        with:
          projectBaseDir: server
          args: |
            -Dsonar.projectKey=${{secrets.PROJECT_KEY}}
            -Dsonar.organization=${{secrets.ORGANISATIONNAME}}
            -Dsonar.projectName=AI-Website
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/node_modules/**
            -Dsonar.cpd.exclusions=**/*.test.js

    # # Quality Gate - blocks pipeline if sonarcloud score fails
    # # e.g. coverage dropped, new bugs introduced, security issues found
    #   - name: sonarcloud Quality Gate Check
    #     uses: SonarSource/sonarcloud-quality-gate-action@master
    #     timeout-minutes: 5
    #     env:
    #       SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
    #       SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

  # Build Docker Image
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, integration-tests, security, sonarcloud]
    permissions:
      id-token: write
      contents: read
      security-events: write
    outputs:
      image-uri: ${{ steps.save-uri.outputs.image-uri }}
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          load: false
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save image uri
        id: save-uri
        run: |
          echo "image-uri=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      # Trivy runs here while image is still in memory
      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "0"

      - name: Upload Trivy Scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  # ─────────────────────────────────────────
  # 8. PUSH TO ECR
  # ─────────────────────────────────────────
  push-to-ecr:
    name: Push to ECR
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check if the image tag exits
        id: check-image
        run: |
          aws ecr describe-images \
            --repository-name ${{ env.ECR_REPOSITORY }} \
            --image-ids imageTag=${{ env.IMAGE_TAG }} \
            --region ${{ env.AWS_REGION }} && echo "exists=true" >> $GITHUB_OUTPUT || echo "exists=false" >> $GITHUB_OUTPUT

      - name: Pull cached image and push to ECR
        if: steps.check-image.outputs.exists == 'false'
        run: |
          docker pull ${{ needs.build.outputs.image-uri }} || true
          docker tag ${{needs.build.outputs.image-uri}} ${{steps.login-ecr.outputs.registry}}/${{env.ECR_REPOSITORY}}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Docker Image
        if: steps.check-image.outputs.exists == 'false'
        run: |
          cosign sign --yes \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Clean up old ECR images (keep last 10)
        run: |
          aws ecr describe-images \
            --repository-name ${{ env.ECR_REPOSITORY }} \
            --query 'sort_by(imageDetails, &imagePushedAt)[:-10].imageDigest' \
            --output text | \
          xargs -I{} aws ecr batch-delete-image \
            --repository-name ${{ env.ECR_REPOSITORY }} \
            --image-ids imageDigest={}

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: push-to-ecr
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    defaults:
      run:
        working-directory: server
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Update Image tag in rollout.yaml
      #   run: |
      #     IMAGE=${{steps.login-ecr.outputs.registry}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
      #     sed -i "s|image:.|image: $IMAGE|g" k8s/rollout.yaml
      #     git config user.email "github-actions@github.com"
      #     git config user.name "Github Actions"
      #     git config pull.rebase true
      #     git pull origin master --rebase
      #     git add k8s/
      #     git commit -m "chore: update image tag to ${{ env.IMAGE_TAG }}" || echo "No changes to commit"
      #     git push

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ env.EKS_CLUSTER_NAME }} \
            --region ${{ env.AWS_REGION }}

      # - name: Update image in Kubernetes manifests
      #   working-directory: ./server
      #   run: |
      #     IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
      #     # Updates the image tag dynamically in your deployment manifest
      #     sed -i "s|image:.*|image: $IMAGE|g" k8s/rollout.yaml

      # - name: Debug folder
      #   run: |
      #     ls -la k8s/

      # - name: Deploy to EKS
      #   working-directory: ./server
      #   run: | 
      #     kubectl apply -f k8s/namespace.yaml
      #     sleep 5
      #     kubectl apply -f k8s/
      

      # - name: Install Argo Rollouts kubectl plugin
      #   run: |
      #     curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
      #     chmod +x kubectl-argo-rollouts-linux-amd64
      #     sudo mv kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts

      # - name: Verify deployment
      #   working-directory: ./server
      #   run: |
      #     kubectl argo rollouts status server -n server-backend --timeout=300s

      # - name: Verify Rollout
      #   working-directory: ./server
      #   run: |
      #     kubectl get rollouts -n server-backend
      - name: Wait for ArgoCD sync
        run: |
           kubectl wait --for=condition=Synced application/server-app -n argocd --timeout=120s
           kubectl wait --for=condition=Healthy application/server-app -n argocd --timeout=120s

  # Notify on failure
  notify:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs:
      [
        lint,
        unit-tests,
        integration-tests,
        security,
        build,
        push-to-ecr,
        sonarcloud,
      ]
    if: failure()
    steps:
      - name: Notify Slack on failure
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "CI PIPELINE FAILED!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🚨 *CI PIPELINE FAILED*\n*Repo:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*Triggered by:* ${{ github.actor }}\n*<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>*"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
